version: "3.6"

services:
  app:
    build: ./
    container_name: lfg-app
    volumes:
      - ./:/valorant-lfg
    ports:
      - "8080:8080"
    expose:
      - "8080"
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=valplayerdbuser
      - POSTGRES_PASSWORD=valplayerdbuserpassword
      - POSTGRES_DB=valplayerdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db: